// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQ9Hc1XViHi_XPcEukbYlarBcDy48cLU',
    appId: '1:383896198927:web:1e4b9dcd46182453b2687a',
    messagingSenderId: '383896198927',
    projectId: 'proje-48f07',
    authDomain: 'proje-48f07.firebaseapp.com',
    storageBucket: 'proje-48f07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6DVH4vIcEHiaKxknA1K5im6AWyNUeVM',
    appId: '1:383896198927:android:266612b9e0e9571bb2687a',
    messagingSenderId: '383896198927',
    projectId: 'proje-48f07',
    storageBucket: 'proje-48f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TCggwObY-iIj9GcEzkR9uYjXLn087eg',
    appId: '1:383896198927:ios:80c24c31c2f30e3ab2687a',
    messagingSenderId: '383896198927',
    projectId: 'proje-48f07',
    storageBucket: 'proje-48f07.appspot.com',
    iosClientId: '383896198927-sqdiinrhv3vrkk1d72umfbus36a64elv.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TCggwObY-iIj9GcEzkR9uYjXLn087eg',
    appId: '1:383896198927:ios:80c24c31c2f30e3ab2687a',
    messagingSenderId: '383896198927',
    projectId: 'proje-48f07',
    storageBucket: 'proje-48f07.appspot.com',
    iosClientId: '383896198927-sqdiinrhv3vrkk1d72umfbus36a64elv.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );
}
